services:
  mongo:
    image: mongo:7.0.14-jammy
    container_name: mongo
    #    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    #    restart: always
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongo:27017
      ME_CONFIG_BASICAUTH: false
